/* Episode log. Times are Pacific (ISO 8601 with offset). To add a night, append an object below and drop its thumb into assets/ep/. */
window.EPISODES = [
  {
    "number": 1,
    "season": 1,
    "night": 1,
    "series_title": "Three Lights and a Gap on the Left",
    "youtube_title": "A Trucker Watches Three Lights on the Ridge, and One Goes Out | Paranormal Radio Drama Ep. 1",
    "premise": "A long-haul trucker calls from a rest stop he doesn't remember reaching. Three lights on the ridge past the fence. Then the left one goes out.",
    "video_id": "GBplrnUil3Q",
    "airs": "2026-09-24T20:03:00-07:00",
    "thumb": "assets/ep/e01.jpg",
    "finale": false,
    "premiere": false
  },
  {
    "number": 2,
    "season": 1,
    "night": 2,
    "series_title": "Call Anyway",
    "youtube_title": "Her Car Keeps Turning Up Facing the Other Way | Paranormal Radio Drama Ep. 2",
    "premise": "A caller keeps finding her car parked facing the other way.",
    "video_id": "RZwCPuWfgt4",
    "airs": "2026-09-25T12:00:00-07:00",
    "thumb": "assets/ep/e02.jpg",
    "finale": false,
    "premiere": false
  },
  {
    "number": 3,
    "season": 1,
    "night": 3,
    "series_title": "September on the Front",
    "youtube_title": "A Voice on His Tape Asks to Be Let In | Paranormal Radio Drama Ep. 3",
    "premise": "A nineteen-year-old on the gas station night shift plays Ray a tape from the empty lot. A voice on it asks to be let in.",
    "video_id": "pekps4JJWbw",
    "airs": "2026-09-25T12:00:00-07:00",
    "thumb": "assets/ep/e03.jpg",
    "finale": false,
    "premiere": false
  },
  {
    "number": 4,
    "season": 1,
    "night": 4,
    "series_title": "Waiting on Four",
    "youtube_title": "A Night Nurse Hears Three Knocks on an Empty Room | Paranormal Radio Drama Ep. 4",
    "premise": "Alone on the fourth floor at 3 a.m., a night nurse hears three knocks on empty room 412, and stays on the line with Ray.",
    "video_id": "aaMR46lChZ8",
    "airs": "2026-09-29T19:00:00-07:00",
    "thumb": "assets/ep/e04.jpg",
    "finale": false,
    "premiere": false
  },
  {
    "number": 5,
    "season": 1,
    "night": 5,
    "series_title": "The Pencil Notes",
    "youtube_title": "An Old Dog Won't Walk Past One Mailbox, and Never Has | Paranormal Radio Drama Ep. 5",
    "premise": "Outside Kearney, Nebraska, an old dog has never once walked past one dented black mailbox. Tonight his owner calls Ray to ask why.",
    "video_id": "sP9yuEYfGVQ",
    "airs": "2026-10-02T19:00:00-07:00",
    "thumb": "assets/ep/e05.jpg",
    "finale": false,
    "premiere": false
  },
  {
    "number": 6,
    "season": 1,
    "night": 6,
    "series_title": "You Kept Talking",
    "youtube_title": "A Fire Lookout's Line Dies, and Ray Keeps Talking for Six Minutes | Paranormal Radio Drama Ep. 6",
    "premise": "In a Bitterroots fire lookout, Lorraine's phone dies mid-call. Ray keeps talking for six minutes. Then she calls back from a number she doesn't know.",
    "video_id": "WBfYQiVjl5Y",
    "airs": "2026-10-06T19:00:00-07:00",
    "thumb": "assets/ep/e06.jpg",
    "finale": false,
    "premiere": false
  },
  {
    "number": 7,
    "season": 1,
    "night": 7,
    "series_title": "Call In First",
    "youtube_title": "A Plough Driver's Three Miles Always Take Eleven Minutes | Paranormal Radio Drama Ep. 7",
    "premise": "Outside Walden, Colorado, a snowplough driver times the same three miles of highway. At plough speed it takes eight minutes. It always takes eleven.",
    "video_id": "7dli96FV4mg",
    "airs": "2026-10-09T19:00:00-07:00",
    "thumb": "assets/ep/e07.jpg",
    "finale": false,
    "premiere": false
  },
  {
    "number": 8,
    "season": 1,
    "night": 8,
    "series_title": "Room Eight, Please",
    "youtube_title": "A Night Baker Marks the Nights His Bread Rises Wrong | Paranormal Radio Drama Ep. 8",
    "premise": "In Chadron, Nebraska, a night baker has marked seventeen nights when the bread rose wrong. Tonight a pan did it again, and he heard a breath.",
    "video_id": "J82Xw3nj2AI",
    "airs": "2026-10-13T19:00:00-07:00",
    "thumb": "assets/ep/e08.jpg",
    "finale": false,
    "premiere": false
  },
  {
    "number": 9,
    "season": 1,
    "night": 9,
    "series_title": "The Seventh and the Fifteenth",
    "youtube_title": "A Man Comes Home to Find He's Been Gone Eight Days | Paranormal Radio Drama Ep. 9",
    "premise": "Outside Ely, Nevada, Wendell comes home with a gas receipt and a tape of footsteps in the wind. The newspaper says he's been gone eight days.",
    "video_id": "Kr-tU9GtbaA",
    "airs": "2026-10-16T19:00:00-07:00",
    "thumb": "assets/ep/e09.jpg",
    "finale": false,
    "premiere": false
  },
  {
    "number": 10,
    "season": 1,
    "night": 10,
    "series_title": "Somebody Knows Where I Am",
    "youtube_title": "No Water Used, but Someone Waves From the Window | Paranormal Radio Drama Ep. 10",
    "premise": "Season 1 finale. A meter reader writes to Ray: one house uses no water at all, yet someone waves from its window every visit.",
    "video_id": "J_Rr97JVbJU",
    "airs": "2026-10-20T19:00:00-07:00",
    "thumb": "assets/ep/e10.jpg",
    "finale": true,
    "premiere": false
  },
  {
    "number": 11,
    "season": 2,
    "night": 1,
    "series_title": "Who Knows Your Hours",
    "youtube_title": "A Dispatcher Hears a Parked Truck Call In Its Mile Markers | Paranormal Radio Drama Ep. 11",
    "premise": "Season 2 opens. A night dispatcher hears a parked, locked truck call in its mile markers, one by one, from her own yard.",
    "video_id": "xWSfMw49_O0",
    "airs": "2026-10-23T19:00:00-07:00",
    "thumb": "assets/ep/e11.jpg",
    "finale": false,
    "premiere": true
  }
];
